package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zghost10/go-best-practices/internal/infra/graphql/generated"
	model1 "github.com/zghost10/go-best-practices/internal/infra/graphql/model"
	usecase "github.com/zghost10/go-best-practices/internal/usecase/user"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model1.CreateUserInput) (*model1.User, error) {
	out, err := r.CreateUserUseCase.CreateUser(usecase.CreateUserInput{
		FirstName: input.FirstName,
		LastName:  input.LastName,
		Email:     input.Email,
		Password:  input.Password,
	})
	if err != nil {
		return nil, err
	}
	return &model1.User{
		ID:        out.ID,
		FirstName: out.FirstName,
		LastName:  out.LastName,
		Email:     out.Email,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model1.User, error) {
	out, err := r.ListUsersUseCase.Execute()
	if err != nil {
		return nil, err
	}
	var users []*model1.User
	for _, u := range out.Users {
		users = append(users, &model1.User{
			ID:        u.ID,
			FirstName: u.FirstName,
			LastName:  u.LastName,
			Email:     u.Email,
		})
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model1.User, error) {
	out, err := r.GetUserUseCase.GetUser(usecase.GetUserInput{Identifier: id})
	if err != nil {
		return nil, err
	}
	return &model1.User{
		ID:        out.ID,
		FirstName: out.FirstName,
		LastName:  out.LastName,
		Email:     out.Email,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
